### ISSUE TITLE
Add multiple elements at a time

### ISSUE THREAD

**Issue by abhinandan1010** [FrederickRider/AutoCompleteBubbleText#6]
I have one arraylist of my models. I want to add all the items from my arraylist to multiedit text so I will iterate the list using for loop, but at that time my application crashed. I got following crash:

05-27 15:33:19.737: E/AndroidRuntime(25597): java.lang.IndexOutOfBoundsException: setSpan (-1 ... -1) starts before 0
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1023)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:611)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:607)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.text.Selection.setSelection(Selection.java:76)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.text.Selection.setSelection(Selection.java:87)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.widget.Editor.onTouchUpEvent(Editor.java:1616)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.widget.TextView.onTouchEvent(TextView.java:8006)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.view.View.dispatchTouchEvent(View.java:8393)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2432)
05-27 15:33:19.737: E/AndroidRuntime(25597):    at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2172)

Please suggest any solution on the same.

**Comment by abhinandan1010** [comment]
Any update on above issue??

**Comment by FrederickRider** [comment]
I have been completely unable to recreate the problem. I need more specific code for what causes the crash. The crash is happens on a touch, which implies that it might be a race condition, but it happens outside of my code, it happens in Android.

Edit: perhaps you can tell me what kind of phone you were using?
